### PR TITLE
Throw exception when attempting to load invalid file

### LINKED ISSUE #29: Break when attempting to load malformed yaml file
Rather than failing silently, we should stop execution and let the user know we were unable to parse the yaml file.

### PR DESCRIPTION
**Pull request by dpikt**
Resolves #29 

This is a breaking change, on the off-chance there are any crazies out there relying on this behavior.

### CODE REVIEW

File: src/utils/readYamlFile.js [hunk 1]
```diff
@@ -8,8 +8,10 @@ function readYamlFile (filePath) {
     return yaml.load(fs.readFileSync(filePath, 'utf8')) || {}
   } catch (e) {
     // Pretty-print file-not-found errors
```
Comment (chawes13) [inline src/utils/readYamlFile.js]: Is this comment still valid?

File: src/utils/readYamlFile.js [hunk 2]
```diff
@@ -8,8 +8,10 @@ function readYamlFile (filePath) {
...
-    if (e.code === 'ENOENT') throw new Error('File not found.')
-    throw e
+    if (e.code !== 'ENOENT') throw e
```
Comment (chawes13) [inline src/utils/readYamlFile.js]: What is special about EN0ENT?

File: test/__snapshots__/read.test.js.snap [hunk 3]
```diff
@@ -0,0 +1,3 @@
+// Jest Snapshot v1, https://goo.gl/fbAQLP
+
+exports[`path defaults to {project_root}/config/application.yml 1`] = `"Figaro: config file not found, skipping load (path=/Users/dpikt/Launchpad/figaro-js/config/application.yml)"`;
```
Comment (chawes13) [inline test/__snapshots__/read.test.js.snap]: Yeah, unfortunately I don't think will pass CI. It doesn't work when running the tests locally on my machine (`path=/Users/chawes/Documents/LaunchPad/opex/...`)

File: test/read.test.js [hunk 4]
```diff
@@ -16,7 +15,7 @@ const getLastCall = fn => last(fn.mock.calls)
 test('path defaults to {project_root}/config/application.yml', () => {
   read()
   const warning = getLastCall(warn)[0]
-  expect(warning).toEqual(`Figaro: (WARNING) file ${ PROJECT_ROOT }/config/application.yml not loaded: File not found.`)
+  expect(warning).toMatchSnapshot()
```
Comment (chawes13) [inline test/read.test.js]: See comment in snapshot file

File: src/utils/readYamlFile.js (hunk 2 above)
Comment (dpikt) [reply src/utils/readYamlFile.js]: No entry, means file wasn't found. We want to skip that case because we don't use config files on heroku and travis.

File: test/__snapshots__/read.test.js.snap (hunk 3 above)
Comment (dpikt) [reply test/__snapshots__/read.test.js.snap]: Now I remember why I didn't use a snapshot before 🤦‍♂

File: src/utils/readYamlFile.js (hunk 2 above)
Comment (chawes13) [reply src/utils/readYamlFile.js]: That seems like useful information to include in a comment

Comment (dpikt) [reply src/utils/readYamlFile.js]: Is the new comment sufficient? Or should I include the bit about heroku/travis? Don't want it to be too idiomatic to our use case.
