### PR TITLE
Log yaml read errors

### LINKED ISSUE #18: Log error if invalid application.yml (or json) file
Right now it just fails silently

### PR DESCRIPTION
**Pull request by dpikt**
Resolves #18

### CODE REVIEW

File: src/utils/omitObjectValues.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ import omitBy from 'lodash.omitby'
 // Omits keys from an object that have an object as their value.
 
 function isObject (val) {
-  return typeof val == 'object'
+  return typeof val === 'object'
```
Comment (rkillackey) [inline src/utils/omitObjectValues.js]: 😱

Comment (dpikt) [reply src/utils/omitObjectValues.js]: Haha
